name: linkero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/star.png
    - assets/link.png
    - assets/final/connect.png
    - assets/final/frameOne.png
    - assets/final/frameTwo.png
    - assets/final/frameThree.png
    - assets/final/frameFour.png
    - assets/final/1.png
    - assets/final/2.png